### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by jonnilundy** [Robert-Frampton/generator-metal-ssg#2]
#### File Structure
|--pages/
   |--index.soy
   |--docs/
      |--index.soy
      |--advancedUsage/
         |--index.md
         |--controllingSurfaces.md
         |--jsAPI.md
       |--features
         |--index.md
         |--errorHandling.md
         |--routes.md
         |--screens.md
         |--theBuildingblocks.md
         |--trackableResources.md
       |--Intro
         |--index.md
         |--capabilities.md
         |--gettingStarted.md
         |--howdoesitwork.md

#### Example of Intro front matter

index.md
---
description: "Intro"
icon: "arrow-right-rod"
layout: "guideIntro"
title: "Intro"
weight: 1
---

howdoesitwork.md
---
description: "How Does It Work"
icon: "arrow-right-rod"
layout: "guideIntro"
title: "How Does It Work"
weight: 2
---

**Comment by Robert-Frampton** [comment]
@jonnilundy 

I think this is a style issue. It looks like the correct elements are getting active classes, but the css isn't targeting those elements the right way. Those style changes can just be made in your project css files.
